import{a as f,S as v,i as c}from"./assets/vendor-Dpd1z_xS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();f.defaults.baseURL="https://pixabay.com";async function g(r,s=1,n=15){const t=`https://pixabay.com/api/?key=47415256-2dfc8fe63cf3afc0ab872a04e&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=${n}`;try{return(await f.get(t)).data}catch(o){console.log("Error fetching pictures:",o.message)}}const h=document.querySelector(".gallery");let u;function b(r){const s=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:o,comments:L,downloads:q})=>`<li class="list-item" >
            <a href="${i}" class="gallery-item">
        <img src="${n}" alt="${e}" class = "gallery-item-img" />
        <div class="info">
            <p class="item"><span class="item-text">Likes</span> <span class="kuu">${t}</span></p>
            <p class="item"><span class="item-text">Wiews</span> <span class="kuu">${o}</span></p>
            <p class="item"><span class="item-text">Comments</span> <span class="kuu">${L}</span></p>
            <p class="item"><span class="item-text">Downlods</span> <span class="kuu">${q}</span></p>
        </div></a></li>`).join("");h.insertAdjacentHTML("beforeend",s),u?u.refresh():u=new v(".gallery-item",{captionsData:"alt",captionDelay:250})}function $(){h.innerHTML=""}const x=document.querySelector(".form-js"),m=document.querySelector(".loader"),a=document.querySelector(".btn-js");document.querySelector(".gallery");x.addEventListener("submit",P);a.addEventListener("click",k);let l=1,d="";const p=15;let y=0;function P(r){if(r.preventDefault(),d=r.target.elements.query.value.trim(),!d){c.error({message:"Please enter a correct query"});return}$(),a.style.display="none",m.classList.remove("hidden"),l=1,g(d,l,p).then(s=>{if(s.hits.length===0){c.info({message:"No images found"});return}y=Math.ceil(s.totalHits/p),b(s.hits),l<y&&(a.style.display="block")}).catch(()=>{c.error({message:"Error fetching images. Please try again."})}).finally(()=>{m.classList.add("hidden")})}async function k(){l+=1,a.style.display="none";const r=document.querySelector(".loading-text");r.style.display="block",r.classList.remove("hidden"),a.disabled=!0;try{const s=await g(d,l,p);b(s.hits);const n=document.querySelectorAll(".gallery-item");if(n.length>0){a.style.display="block",r.style.display="none";const e=n[0].getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}l===y&&(a.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Error fetching images. Please try again."}),r.style.display="none",a.style.display="none"}finally{r.classList.add("hidden"),a.disabled=!1}}
//# sourceMappingURL=index.js.map
