import{S as m,i as o}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function d(i){return fetch(`https://pixabay.com/api/?q=${i}&image_type=photo&orientation=horizontal&safesearch=true&key=47415256-2dfc8fe63cf3afc0ab872a04e`).then(s=>{if(!s.ok)throw new Error(s.statusText);return s.json()})}const u=document.querySelector(".gallery");let c;function g(i){const r=i.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:n,comments:f,downloads:p})=>`<li class="list-item" >
            <a href="${a}" class="gallery-item">
        <img src="${s}" alt="${e}" class = "gallery-item-img" />
        <div class="info">
            <p class="item"><span class="item-text">Likes</span> <span class="kuu">${t}</span></p>
            <p class="item"><span class="item-text">Wiews</span> <span class="kuu">${n}</span></p>
            <p class="item"><span class="item-text">Comments</span> <span class="kuu">${f}</span></p>
            <p class="item"><span class="item-text">Downlods</span> <span class="kuu">${p}</span></p>
        </div></a></li>`).join("");u.innerHTML=r,c?c.refresh():c=new m(".gallery-item",{captionsData:"alt",captionDelay:250})}function y(){u.innerHTML=""}const h=document.querySelector(".form-js"),l=document.querySelector(".loader");h.addEventListener("submit",L);function L(i){i.preventDefault();const r=i.target.elements.query.value.trim();if(!r){o.error({message:"Please enter a correct query"});return}y(),l.classList.remove("hidden"),d(r).then(s=>{if(s.hits.length===0){o.info({message:"No images found"});return}g(s.hits)}).catch(s=>{o.error({message:"Error fetching images. Please try again."})}).finally(()=>{l.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
